# Generated by Django 4.1 on 2022-11-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePrograma', models.CharField(max_length=30, verbose_name='Nombre del programa:')),
                ('localizacion_cel', models.CharField(max_length=30, verbose_name='Localización del CEL:')),
                ('duracion', models.CharField(max_length=30, verbose_name='duración del programa:')),
                ('nombreCEL', models.CharField(max_length=30, verbose_name='Nombre del CEL:')),
                ('vacantes', models.IntegerField(verbose_name='Número de vacantes disponibles:')),
            ],
        ),
    ]
