# Generated by Django 4.1 on 2022-11-08 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0002_postularprograma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postularprograma',
            old_name='id_programa',
            new_name='id',
        ),
    ]
