# Generated by Django 4.1 on 2022-11-08 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0003_rename_id_programa_postularprograma_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postularprograma',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programas.programa', verbose_name='ID del programa: '),
        ),
    ]
